### ISSUE TITLE
feat: rooted support

### ISSUE THREAD

**Issue by Ramam001** [taku-nm/auto-cli#21]
Is there anyway to do it in rooted phone?

**Comment by taku-nm** [comment]
auto-cli does not currently support rooted devices, however, regular ReVanced cli does. Either use it with its documentation, or use the regular ReVanced manager.
I will likely add root support in the future.

**Comment by Letus252** [comment]
Are there any updates on rooted support?

**Comment by taku-nm** [comment]
I want to look into it either this evening or tomorrow. It should be fairly easy, I just need to know what i would need to do as I have no experience with root installs.

**Comment by taku-nm** [comment]
Looked into this.
Unfortunately this is out of scope for this tool as it does require significant user action.
So please use CLI manually or use magisk modules.
