### ISSUE TITLE
How do I pick and choose patches, or use a different version of TikTok?

### ISSUE THREAD

**Issue by DrReddP** [taku-nm/auto-cli#25]
So TikTok Revanced, the playback speed patch actually breaks the ability to adjust the playback speed at all. This is a known issue with TikTok revanced, but I would like to try patching without the playback speed patch, or patching the older 30.7.4 that worked properly before. How do I tell the auto-CLI to use a different version, or select different patches?

**Comment by taku-nm** [comment]
You cant specify to use a different version of TikTok, however, you can use the custom option to define whatever you like. Simply select custom and follow the instructions. Download the APK you want from APKmirror and place it in the folder as instructed. You do not need to provide patches. You can then customize the patch selection as instructed.

**Comment by DrReddP** [comment]
so the old version of the revanced manager was able to patch an older version of TikTok just fine, and all of the patches worked. how do I get myself the older version of revanced Manager that will properly modify the older version of TikTok so that all of the patches properly work?

I did try just using my own older APK with your current auto CLI but it just said the patches aren't compatible. I also tried using the recommended version but simply not doing the playback speed patch with the issue is still the same either way

**Comment by taku-nm** [comment]
You can see here which patches are compatible with what version.
https://revanced.app/patches?pkg=com.ss.android.ugc.trill
Your older version will not be compatible with all of the patches.
There is no point in using an older version of the manager, as that app always pulls the most recent patches. 

What I'd recommend is:
1. Select custom
2. Select to download TikTok from the app list
3. When it prompts you to select patches, simply do
`-e "Playback speed"`

**Comment by DrReddP** [comment]
I already followed all of the instructions, I went all the way through and had it apply all of the default patches except for the playback speed one as the instructions in the CLI told me to. it successfully built an APK for me with all of the patches except for the playback speed patch, but the bug still persists. you cannot adjust the playback speed on TikTok if it has been patched by revanced in any way apparently.

The older version of the revanced manager was able to patch older versions of TikTok just fine. as in, before the current version, All of the patches were working. how exactly do I revert to the older version of TikTok using the older patches that actually worked?

**Comment by taku-nm** [comment]
Thing is, the patches didn't actually change recently. All that has changed is the restriction to the latest working version. 30.8.4

You can force it to ignore the version checks by also passing `--force` alongside the exclusion of the playback speed patch.

You can also specify an old version of the patches themselves using the Custom option and providing your own patches.jar which you can download from the revanved patches repository / releases.

**Comment by DrReddP** [comment]
that is well above my head. I'm really just a user. this is the first time I've even looked at a command line since like 1998

**Comment by taku-nm** [comment]
I checked my version, it also appears to be missing the playback speed option.
I'll dig into this a little deeper later.

**Comment by DrReddP** [comment]
they're aware of it over on the revanced CLI GitHub.

**Comment by taku-nm** [comment]
Can you link me to it?

**Comment by DrReddP** [comment]
yeah it took a minute for me to dig through my notifications

https://github.com/ReVanced/revanced-patches-template/issues/464
