### ISSUE TITLE
Patched Relay, 27 trackers.

### ISSUE THREAD

**Issue by r3538987** [taku-nm/auto-cli#26]
Default 1.2.40 Relay Pro app has 5 trackers by default.
One patched with ReVanced, also with 5.
Used auto-cli, results with app being pushed from 12MB to 16MB and one contains 27 trackers. 
I would understand if few more occurred, but that much.

How it came be, why amount is increased that drastically?

**Comment by taku-nm** [comment]
This is not related to auto-cli. I'm not really sure what you mean by trackers, but all modifications are done by revanced patches.
You could either open an issue in the revanced patches repo about this or (the better approach) would be to ask in the development channel in discord about this.

**Comment by r3538987** [comment]
Probably this is the reason, app with 5 trackers is the Pro one, and one from apkmirror is the non-pro which previously was supposed to show an ads. 
This also explains difference in size. Case closed. 
Script will patch Pro version as well, just replace apk file when you are on step with key.
