### ISSUE TITLE
Hashes not correct

### ISSUE THREAD

**Issue by CrazyWolf13** [taku-nm/auto-cli#32]
There seems to be some problems regarding hashes and checking them.
![image](https://github.com/taku-nm/auto-cli/assets/96661824/395f1bc5-8502-4167-a941-28f65833a6c5)

**Comment by taku-nm** [comment]
No the issue is the fact that it fails to write to the path specified because it is lacking in permissions.
Execute the script at a location at which your current user has permission to write files.

**Comment by CrazyWolf13** [comment]
Yes, Thanks
