### ISSUE TITLE
update patch list

### ISSUE THREAD

**Issue by VixenSugo** [taku-nm/auto-cli#34]
pls update patch list. for example: twitter patch in list is very old and now it changed as X v 10.33.0
add [revanced patch](https://github.com/ReVanced/revanced-patches) for X (Twitter) and [crimera ](https://github.com/crimera/piko)patch if you can (revancify added that)
thank you for this project

**Comment by taku-nm** [comment]
The majority of apps available are restricted by what version is currently suggested to patch using the regular ReVanced patches.
In general, this project does not focus on the most recent app update, but rather on stability. With that said, the following apps have now been updated:
- Twitter
- Lightroom
- Reddit

The fork by crimera for Twitter has been added as "Twitter piko by crimera"
