### ISSUE TITLE
[Feature request] Port this script for macOS and Linux users

### ISSUE THREAD

**Issue by hazelshantz** [taku-nm/auto-cli#35]
Hello there. just wanted to request this script to be ported to macOS and Linux users so it makes it easier to patch.

**Comment by bogadana** [comment]
personally I prefer tacos

**Comment by taku-nm** [comment]
Hi, this script is already fairly niche as it is pretty much just intended for the cases where revanced manager fails.
Given that a windows user is much less likely to be technically inclined than a Linux user, and that MacOS users probably don't have an android phone to begin with, the user base for a bash variant of this already niche script is incredibly tiny. Any Linux user is expected to be able to use the terminal and follow the documentation. If one is stuck, they can simply ask in support.

Additionally to that, I don't have much experience with bash and generally find it a pain to work with.

Ofc, anyone is free to write a bash clone of this script and use the input3.json as a data source.
