### ISSUE TITLE
Cannon install autocli. Files are missing from discord's CDN?

### ISSUE THREAD

**Issue by yumyai** [taku-nm/auto-cli#36]
Hi, I started installing autocli and appearanly,  some files are missing. Here is the screenshot.
![Screenshot 2024-04-20 091126](https://github.com/taku-nm/auto-cli/assets/100079/74e50fd3-6289-4af7-b92b-5511710fdabf)

**Comment by taku-nm** [comment]
Thanks for this notice.
Discord seems to now actually enforce their expired links while also reducing down the validity from 2 weeks down to 1 day. 
I have adjusted the refresher accordingly
[with this commit](https://github.com/taku-nm/auto-cli/commit/2db34ef5da11045025654cc009751856dfc9b9e6)

Simply run the script again

**Comment by michelito** [comment]
I'm having the same issue this week. Can't find the JDK on discord. Downloaded the azul jdk manually, and removed the check in the batch file. Ran into the same issue trying to download Relay.apk. Downloaded from apkmirror and tried to patch, but it keeps telling me it can't find the apk...
I'm stuck.

**Comment by taku-nm** [comment]
The script relies heavily on the input3.json to be updated by github actions. Unfortunately, github actions are somewhat unreliable lately, hence it did not run yesterday. I have now scheduled it manually once more and will have to look into a more reliable solution...

Simply run the unmodified script again.

**Comment by michelito** [comment]
You're the best !
