### ISSUE TITLE
Revanced Extended Not Showing Up

### ISSUE THREAD

**Issue by Lorograch1** [taku-nm/auto-cli#37]
As the title suggests, Revanced Extended is not showing in the list of available apps in the CLI. Is this not available anymore?

**Comment by taku-nm** [comment]
Correct, as seen here:
https://github.com/taku-nm/auto-cli/commit/b92e2de342ee8a43879e2d1f70e7297267820856

Extended has been removed because it is deprecated and the playback issue fix is only in the main patches repo
