### ISSUE TITLE
#Feature Request: Patch Option Selection

### ISSUE THREAD

**Issue by ahXN00** [taku-nm/auto-cli#38]
When i select any app to patch, it uses the default value given , can you maybe make a selection menu with yes/no where we can select which patch options we want to add/.

**Comment by taku-nm** [comment]
I'm not sure if you're talking about patch options or including and excluding patches.
either way, both of these cases are handled interactively with the custom menu. (Select A and nothing else)

Based on your inputs, the script will either list all patches available or tell you to look at the available patches on revanced.app. Additionally it gives you the Syntax on how to include or exclude any given patch.

Regardless of your input, custom mode will always present you with the patch options JSON file, generated for the patch bundle specified.

making either the patch selection or patch options truly interactive with sort of menu to navigate, is not feasible.

**Comment by ahXN00** [comment]
Thank you for the reply, i didn't notice the custom option , that's what i was asking about.
