### ISSUE TITLE
Outdated Revanced Tools

### ISSUE THREAD

**Issue by Mazino-Urek** [taku-nm/auto-cli#39]
Auto-cli has not updated Revanced Tools for quite some time. Current Revanced toolchain versions are:

revanced-integrations  [v1.13.0](https://github.com/ReVanced/revanced-integrations/releases/tag/v1.13.0)

revanced-patches  [4.13.0](https://github.com/ReVanced/revanced-patches/compare/v4.12.0...v4.13.0)

Current versions in the auto-cli:

```
  revanced-cli-4.6.0-all.jar validated
  revanced-patches-4.11.0.jar validated
  revanced-integrations-1.11.1.apk validated
```

**Comment by taku-nm** [comment]
will update today (probably)

**Comment by taku-nm** [comment]
tools updated

**Comment by Mazino-Urek** [comment]
Thanks!
