### ISSUE TITLE
revanced-cli-ouput overwrites other patches

### ISSUE THREAD

**Issue by Sooperfish** [taku-nm/auto-cli#4]
I thought I'd run this tool for all the apps and then copy everything over to my phone, just to see a measly two .APKs in the folder.
Would be nice if the patches didn't overwrite each other 👍

**Comment by Sooperfish** [comment]
Ohh they are in local appdata 🤯

**Comment by Sooperfish** [comment]
I thought they were in local appdata, but these are .backup files. What do I do with those?

**Comment by Sooperfish** [comment]
you can delete this i cant read

edit: a shortcut to the backups generated in the revanced-cli-ouput folder and a readme/blank file in the backup folder explaining you have to rename them would be nice

**Comment by taku-nm** [comment]
noted for 1.28
