### ISSUE TITLE
Can you please also add Google Photos in the list?

### ISSUE THREAD

**Issue by mukul23** [taku-nm/auto-cli#41]

**Comment by taku-nm** [comment]
will be done once cli 5 releases

**Comment by mian196** [comment]
> will be done once cli 5 releases

v5 already released.

**Comment by taku-nm** [comment]
This issue will be closed as this project is coming to it's logical end.

With the release of ReVanced Manager v1.23, all relevant matters such as ARMv7 support and heap memory allocation issues, have been addressed and thereby made this CLI wrapper redundant.

To continue seamlessly updating your patched app, copy the keystore and keystore password from ```%localappdata%/revanced-cli/keystore``` and import it in the manager.
