### ISSUE TITLE
[FR] Adding some apps

### ISSUE THREAD

**Issue by CrazyWolf13** [taku-nm/auto-cli#42]
Hi
Thanks for maintaining this awesome tool!

Any plans to include the following apps:
- Duolingo
- Photomath
- Strave
- Soundcloud

Huge thanks!

**Comment by taku-nm** [comment]
This issue will be closed as this project is coming to it's logical end.

With the release of ReVanced Manager v1.23, all relevant matters such as ARMv7 support and heap memory allocation issues, have been addressed and thereby made this CLI wrapper redundant.

To continue seamlessly updating your patched app, copy the keystore and keystore password from ```%localappdata%/revanced-cli/keystore``` and import it in the manager.
