### ISSUE TITLE
Update Revanced Packages

### ISSUE THREAD

**Issue by Mazino-Urek** [taku-nm/auto-cli#43]
Both `revanced-cli` and `revanced-patches` has been updated to version 5.0.

**Comment by taku-nm** [comment]
This issue will be closed as this project is coming to it's logical end.

With the release of ReVanced Manager v1.23, all relevant matters such as ARMv7 support and heap memory allocation issues, have been addressed and thereby made this CLI wrapper redundant.

To continue seamlessly updating your patched app, copy the keystore and keystore password from ```%localappdata%/revanced-cli/keystore``` and import it in the manager.
